name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: 11.3.0

      - uses: actions/setup-node@v6
        with:
          node-version: 24.15
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint:fix

      - run: pnpm format

      - run: pnpm build
